<?php
	$this->load->view(getLang().'/empresa/aba');
?>
<section class="container empresa">
	<h1 class="title"><?=lang('defualt_menu_sobre'); ?></h1>

	<img class="banner" alt="" src="<?=base_url('assets/img/banners/banner-empresa.jpg'); ?>">

	<div class="descricao header">
		Celulose Riograndense, a part of CMPC group, is a Gaúcho company present in the international market of eucalyptus short fiber cellulose. It has a factory in Guaíba municipality, now occupying an area of 106 hectares, and invests on forest culture as source for supplying sustainable raw material, in order to produce riches for Rio Grande do Sul state and its citizens.
		<br><br>
		For Celulose Riograndense, growing together with Gaúchos is more than a priority, it is a commitment. A commitment with who works in the company, with Guaíba citizens, and with those that transform Riograndense soil in a better place to live.
	</div>

	<h3 id="diferenciais">Differentials</h3>
	<div class="descricao">
		A total of 99.7% of residues resulting from the cellulose manufacturing process are recycled.
	</div>

	<h4>Advanced effluent treatment</h4>
	<div class="descricao">
		That transforms it in one of the few factories with this structure in the world.
	</div>

	<h4>Minimum impact</h4>
	<div class="descricao">
		In the return of treated effluent to Guaíba Lake.
	</div>

	<h4>Energy Co-Generation</h4>
	<div class="descricao">
		A total of 80% of the energy necessary for producing cellulose is generated by the very factory.
	</div>

	<h3 id="diferenciais" class="header">Manufacturing Processes</h3>

	<h4>Energy Generation</h4>
	<div class="descricao">
		The company does generate energy for its use from residues from cellulose production process. These residues are burnt<br>
		in a boiler and the produced steam cause turbines to work. Thus, we have steam and electric energy to meet the factory needs.<br>
		The internal energy production could support a city with 200 thousand inhabitants.
	</div>

	<h4>Chemical Plants</h4>
	<div class="descricao">
		Most chemicals used by Celulose Riograndense are internally produced. The excess is sold to the market for the sectors of water treatment, cleaning products, plastics, rubbers, and food.
	</div>

	<h4>Effluent Treatment</h4>
	<div class="descricao">
		The water for cellulose production process comes from Guaíba Lake. After its use, it passes through primary, secondary, and tertiary treatments to be returned to the lake again. Celulose Riograndense was a pioneer in using this technology, and now, among more than one thousand cellulose factories existing in the world, less than ten use this innovation, what ensures excellent quality to the effluent. The slime generated in this plant passes through a composting process to be later sold to the market as organic fertilizer, replacing the use of black soil removed from puddles and bushes.
	</div>

	<h4>Paper</h4>
	<div class="descricao">
		Celulose Riograndense has a paper producing unit with capacity to generate 60 thousand metric tons per year, supplying a diversified market in printing and writing sectors.
	</div>

	<br><br>

	<img class="esquema" alt="" src="<?=base_url('assets/img/'.getLang().'/esquema.jpg'); ?>">

	<div class="clear"></div>
</section>