<?php

	$this->load->view(getLang().'/expansao/aba');

?>
<section class="container expansao">
	
	<h1 class="title">Project Guaiba 2</h1>

	<img class="banner" alt="" src="<?=base_url('assets/img/banners/banner-expansao.jpg'); ?>">
	<br><br>
	<div class="titulo">A PROJECT</div>

	<div class="expansao-body">
		In December 2012, Rio Grande do Sul received confirmation of the largest private investment in its history. Riograndense Cellulose, headquartered in Guaiba, announced that 2015 will be invested over $ 5 billion to expand its plant. Divided into three major areas: Industrial, Forestry and infrastructure, the project will increase by more than three times the production capacity of the unit. Today, the company owns 214,000 acres of land, of which 81 thousand are intended for environmental preservation.
		<br><br>
		The new plant will require hiring local companies, creating more development, business, taxes, jobs and better living conditions throughout the region. More than 7000 direct jobs and 17,100 indirect will be generated by 2015, when the plant will enter service. Later will be created over 2,500 direct jobs.
		<br><br>
		In addition to the investment in the work, the expansion will generate during the construction phase, U.S. $ 102 million payment to the State of ICMs. With the coming into operation, the annual generation of foreign exchange will be approximately £ 1.4 billion. Currently, the plant produces Guaiba 450 000 tonnes of pulp per year. With the expansion, will 1,750 tonnes per year and 100% of marketed production.
		<br><br>
		The expansion will bring numerous benefits, leveraging the supply chain with the participatory incentive for local businesses, creating conditions for these to expand their market share, improving its processes and modernizing its industrial parks, helping in the growth and development of the state as a whole.
	</div>

	<div class="expansao-bar">
		<img src="<?=base_url('assets/img/expansao-sidebar.jpg'); ?>">
	</div>

</section>